--Crear tabla TBL_BRANDS para las marcas
DROP TABLE IF EXISTS TBL_BRANDS;

CREATE TABLE TBL_BRANDS (
    BRAND_ID INT  NOT NULL AUTO_INCREMENT,
    BRAND_NAME CHAR(50),
    CONSTRAINT PK_TBL_BRANDS PRIMARY KEY (BRAND_ID)
);

--Crear tabla TBL_PRICES para los precios
DROP TABLE IF EXISTS TBL_PRICES;

CREATE TABLE TBL_PRICES (
    PRICE_LIST BIGINT NOT NULL AUTO_INCREMENT(10,1),
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE DECIMAL(6,2),
    CURR CHAR(3),
    CONSTRAINT PK_TBL_PRICES PRIMARY KEY (PRICE_LIST)
);

ALTER TABLE TBL_PRICES
ADD FOREIGN KEY (BRAND_ID) REFERENCES TBL_BRANDS(BRAND_ID);

CREATE INDEX index_prices
ON TBL_PRICES (START_DATE, END_DATE, PRODUCT_ID, BRAND_ID);